// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyf8gbh4xDQo23E3pdVQ_xNPX6yAhFPO8',
    appId: '1:262386306290:ios:f35ec55d23f33deac0546b',
    messagingSenderId: '262386306290',
    projectId: 'dormdeals-7a3a5',
    storageBucket: 'dormdeals-7a3a5.appspot.com',
    iosBundleId: 'com.example.dormdeals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyf8gbh4xDQo23E3pdVQ_xNPX6yAhFPO8',
    appId: '1:262386306290:ios:f35ec55d23f33deac0546b',
    messagingSenderId: '262386306290',
    projectId: 'dormdeals-7a3a5',
    storageBucket: 'dormdeals-7a3a5.appspot.com',
    iosBundleId: 'com.example.dormdeals',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyV_5JAeToVw0ncoKxByOQSOUR8JkEMFA',
    appId: '1:262386306290:web:607217478b77cadcc0546b',
    messagingSenderId: '262386306290',
    projectId: 'dormdeals-7a3a5',
    authDomain: 'dormdeals-7a3a5.firebaseapp.com',
    storageBucket: 'dormdeals-7a3a5.appspot.com',
    measurementId: 'G-X3G1QQ3W08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChzXdXYv-rdjD9ex0gdoevtvx_yH8Nhi4',
    appId: '1:262386306290:android:997afa380c972d55c0546b',
    messagingSenderId: '262386306290',
    projectId: 'dormdeals-7a3a5',
    storageBucket: 'dormdeals-7a3a5.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyV_5JAeToVw0ncoKxByOQSOUR8JkEMFA',
    appId: '1:262386306290:web:a97d9091d0798913c0546b',
    messagingSenderId: '262386306290',
    projectId: 'dormdeals-7a3a5',
    authDomain: 'dormdeals-7a3a5.firebaseapp.com',
    storageBucket: 'dormdeals-7a3a5.appspot.com',
    measurementId: 'G-9RTRXH5SXW',
  );

}